;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-line-dwim
        c-electric-brace
        c-electric-colon
        c-electric-lt-gt
        c-electric-paren
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        c-macro-expand
        electric-newline-and-maybe-indent
        electric-pair-delete-pair
        eval-and-replace
        eval-last-sexp
        eval-print-last-sexp
        kill-region
        persp-prev
        subword-left
        subword-right
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        ))
