;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backspace-some
        backward-sexp
        beginning-of-line-dwim
        c-electric-brace
        c-electric-colon
        c-electric-lt-gt
        c-electric-paren
        c-electric-pound
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        c-macro-expand
        comment-line
        dired-mark
        dired-unmark
        dired-unmark-all-marks
        diredp-next-line
        diredp-previous-line
        drag-stuff-right
        drag-stuff-up
        electric-newline-and-maybe-indent
        electric-pair-delete-pair
        elpy-nav-forward-indent
        erl-openparen
        erlang-electric-comma
        erlang-electric-gt
        erlang-electric-semicolon
        eval-and-replace
        eval-last-sexp
        eval-print-last-sexp
        forward-sexp
        kill-region
        org-beginning-of-line
        org-ctrl-c-minus
        org-end-of-line
        org-return-indent
        org-self-insert-command
        persp-prev
        smex
        subword-left
        subword-right
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        ein:worksheet-execute-cell-and-goto-next
        handle-switch-frame
        imenu
        persp-switch
        projectile-run-project
        save-some-buffers
        ))
